// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as AppWrapper$ReasonPlayground from "./AppWrapper.js";

ReactDOMRe.renderToElementWithId(React.createElement(AppWrapper$ReasonPlayground.make, { }), "root");

export {
  
}
/*  Not a pure module */
